name: barrage_flutter
description: Barrage Widget
version: 0.0.1
homepage: http://github.com/Dorbmon

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: